; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev          ; or esp32-s3-devkitc-1 etc. if using S3
framework = arduino       ; ← this is the key line
monitor_speed = 115200
lib_deps = 
    ; Recommended starters:
    https://github.com/openenergymonitor/EmonLib.git   ; great for power calcs
    ; or knolleary/PubSubClient@^2.8   ; for MQTT if needed
build_flags = 
    -D CORE_DEBUG_LEVEL=1